Unit tests
HowProgrammingWorks/Exams pull request #122
Opened 2022-01-16 00:54 UTC by nieopierzony

Related to #120

The idea was taken from online olympiads.In addition to the known tests, it is also tested on N random ones.  The bad thing is that you have to have 100% working code to create the expected answer. 

Test runner runs tests by task names, which are passed via console arguments. E. g. `npm test -- distinct`

2022-01-26 21:34 UTC, tshemsedinov requested changes
- We do not need random arrays in this tests, just a few predefined examples
- This test should apply all test cases for multiple implementations of each task

2022-01-26 21:34 UTC, tshemsedinov commented on package.json
> +  "description": "",
```suggestion
  "private": true,
```

2022-01-26 21:34 UTC, tshemsedinov commented on package.json
> +  "author": "",
```suggestion
```

2022-01-26 21:34 UTC, tshemsedinov commented on package.json
> +    "url": "git+https://github.com/nieopierzony/Exams.git"
```suggestion
    "url": "https://github.com/HowProgrammingWorks/Exams"
```

2022-01-26 21:34 UTC, tshemsedinov commented on package.json
> +    "url": "https://github.com/nieopierzony/Exams/issues"
```suggestion
    "url": "https://github.com/HowProgrammingWorks/Exams/issues"
```

2022-01-26 21:34 UTC, tshemsedinov commented on package.json
> +  }
```suggestion
  }
```

2022-01-27 16:42 UTC, nieopierzony commented on test/distinct.task.js
> +  const cachedInput = JSON.parse(JSON.stringify(testCase.input));
For some reason `const cachedInput = [...testCase.input];` doesn't work

2022-01-27 17:25 UTC, nieopierzony commented
I decided to use child_process to call the code linter. I could use the npm feature to insert arguments inside the command `npm lint:task --task=distinct -> eslint Tasks%npm_config_task%.js` and it would work, but only on Windows. On Linux is a different templates, so `eslint Tasks/${npm_config_task}.js` but it wouldn't work on Windows ._.
So I decided to find a compromise by using child processes inside the test runner

2022-01-27 23:45 UTC, nieopierzony commented
I'm also considering storing cases not in a huge JSON file, but exporting it from each task along with the function

2022-02-01 14:21 UTC, tshemsedinov commented
Closed in favour of https://github.com/HowProgrammingWorks/Exams/pull/128 but you can port come test case to this structure

2022-02-01 14:21 UTC, closed without merging