Exams
HowProgrammingWorks/Exams pull request #157
Opened 2023-01-08 16:55 UTC by igaryakqwe

Did the tasks for the exam, following @tshemsedinov recommendations.
I hope it wasn't bad.

2023-01-13 15:33 UTC, mibal-ua requested changes
Код красивий, але є питання.

2023-01-13 15:33 UTC, mibal-ua commented on Tasks/day.js
> +const getDayNumber = (num) => {
Функція приймає число? Чи назву дня? Якщо приймає число, то залишай `num`, якщо ж день, то треба перейменувати `num` на інше.

2023-01-13 15:33 UTC, mibal-ua commented on Tasks/day.js
> +      return ++i;
Тут краще повертати `i + 1;` бо так не буде зайвої операції запису в змінну `i` та буде більш читаємо.

2023-01-13 15:33 UTC, mibal-ua commented on Tasks/random.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
Тут все супер, тільки в початковому коді була можливість використовувати функцію з одним аргументом.
В твоїй версії цього нема.

2023-01-13 15:33 UTC, mibal-ua commented on Tasks/sample.js
> +  const random = Math.floor(Math.random() * arr.length);
але це не критично

2023-01-14 12:50 UTC, igaryakqwe commented on Tasks/day.js
> +const getDayNumber = (num) => {
fixed

2023-01-14 12:54 UTC, igaryakqwe commented on Tasks/day.js
> +      return ++i;
+

2023-01-14 13:01 UTC, igaryakqwe commented on Tasks/sample.js
> +  const random = Math.floor(Math.random() * arr.length);
виправив

2023-01-14 13:08 UTC, mibal-ua reviewed
Пліз фікс

2023-01-14 13:08 UTC, mibal-ua commented on Tasks/day.js
> +  const end = -1;
Для чого тут виносити цю змінну `end`? Вона ніде окрім як в кінці не використовується.

2023-01-14 13:13 UTC, igaryakqwe commented on Tasks/day.js
> +  const end = -1;
fixed

2023-01-23 21:38 UTC, tshemsedinov approved these changes
LGTM (looks good to me)

2023-01-23 21:38 UTC, tshemsedinov commented on Tasks/day.js
> +  for (let i = 0; i < days.length; i++) {
Alternative: `for (const [i, name] of DAYS.elements())`

2023-01-23 21:38 UTC, tshemsedinov commented on Tasks/day.js
> +const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
```suggestion
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
```

2023-01-23 21:38 UTC, tshemsedinov commented on Tasks/sample.js
>  };
It's better to decompose extracting `random` as a separate function

2023-01-23 21:39 UTC, closed without merging