Exams by Tytianiuk Artem
HowProgrammingWorks/Exams pull request #161
Opened 2023-01-09 13:28 UTC by tytianiuk

I am a student of IM-22 group, I did the assignment for the exam.

2023-01-09 14:03 UTC, mibal-ua commented on Tasks/month.js
> +'use strict';
Тут зі `'use strict';` така ж тема

2023-01-09 14:10 UTC, mibal-ua commented on Tasks/month.js
> +const getNumberMonth = (nameMonth) => {
я би назвав функцію `getMonthNumber()` або `getNumberOfMonth()`. бо `getNumberMonth` звучить як "отримати число місяць".

2023-01-09 14:13 UTC, mibal-ua commented on Tasks/month.js
> +  const lowerNameMonth = nameMonth.toLowerCase();
`lowerNameMonth` звучить як "занижене ім'я місяць", коректніше `lowerMonthName`.

2023-01-09 14:16 UTC, mibal-ua commented on Tasks/month.js
> +    if (lowerNameMonth.startsWith(MONTHS[i])) return ++i;
тут би я повернув `i + 1;` але то питання стилю та читабельності.

2023-01-09 19:34 UTC, mibal-ua approved these changes
Супер, я задоволений 😊

2023-01-10 19:29 UTC, BoqdanY requested changes
Your cod is excelent, but you have to use better name for variables.

2023-01-10 19:29 UTC, BoqdanY commented on Tasks/filter.js
> +  for (const object of arr) {
Instead `object` it's better to use `elem` or `element`

2023-01-10 19:29 UTC, BoqdanY commented on Tasks/filter.js
> +    if (typeof object === type) {
It's better here to use `elem` or `element` instead `object`

2023-01-10 19:29 UTC, BoqdanY commented on Tasks/filter.js
> +      result.push(object);
Here also better use `elem` or `element` instead `object`

2023-01-10 19:57 UTC, BoqdanY commented
Good job!

2023-01-10 19:59 UTC, BoqdanY approved these changes

2023-01-24 17:14 UTC, tshemsedinov commented on Tasks/month.js
> +const months = [
Naming hint: `MONTHS`

2023-01-24 17:14 UTC, closed without merging