Exams by Maksym Dikhtiar
HowProgrammingWorks/Exams pull request #162
Opened 2023-01-09 17:17 UTC by magicvegetable

2023-01-09 18:04 UTC, basarabst requested changes

2023-01-09 18:04 UTC, basarabst commented on Tasks/replace.js
> +      str = str.substring(substrIndex + substrLen);
Try not to change input arguments, it's bad practice.
In general, there is a ready-made [string method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) for this task.
`String.prototype.replace()`

2023-01-09 21:07 UTC, basarabst approved these changes
☑️

2023-01-22 17:10 UTC, tshemsedinov reviewed
Not an optimal but enough to be accepted. Always use `;` and return-earlier pattern.

2023-01-22 17:10 UTC, closed without merging