Exams by Kseniia Horai
HowProgrammingWorks/Exams pull request #166
Opened 2023-01-10 08:16 UTC by KseniiaHorai

1) validate.js and sum.js (with commits)
2) section.js, sample.js, reverse.js (fixed without commits)

2023-01-17 18:28 UTC, notnuff approved these changes
All fine!

2023-01-23 16:27 UTC, tshemsedinov requested changes
You need linter and or fix code alignment manually

2023-01-23 16:27 UTC, tshemsedinov commented on Solutions/reverse.js
> +    return object;
Try not to change incoming parameters but generate new object

2023-01-23 16:27 UTC, tshemsedinov commented on Solutions/reverse.js
> +        delete object[item];
Try to avoid `delete`

2023-01-23 16:27 UTC, tshemsedinov commented on Solutions/section.js
> +     } else {
We do not need else here

2023-01-23 16:27 UTC, tshemsedinov commented on Tasks/validate.js
> +const isValid = (name) => {
Naming hint: better name `validate` or `check` (verbs)

2023-01-23 16:27 UTC, closed without merging

2023-01-23 18:24 UTC, KseniiaHorai commented on Tasks/sum.js
> +    if (typeof(item) === 'number') {
Fixed here:
https://github.com/KseniiaHorai/Exams/blob/master/Tasks/sum.js

2023-01-23 18:24 UTC, KseniiaHorai commented on Tasks/validate.js
> +      if ( letter.toLowerCase().charCodeAt(0) < 97 || letter.toLowerCase().charCodeAt(0) > 122) {
Fixed code here:
https://github.com/KseniiaHorai/Exams/blob/master/Tasks/validate.js