Exams
HowProgrammingWorks/Exams pull request #169
Opened 2023-01-11 10:33 UTC by merrymike-noname

Written by Mykhailo Kovalenko IM-22

2023-01-11 14:28 UTC, mibal-ua requested changes
НА ДОПКУ

2023-01-11 14:28 UTC, mibal-ua commented on Tasks Kovalenko (Java)/Ip.java
> +        else return null;
Тут нам не треба `else`, бо якщо `return` вище не спрацює, то все одно програма пойде на 19 строчку

2023-01-11 14:28 UTC, mibal-ua commented on Tasks Kovalenko (Java)/Ip.java
> +        }
для `if` на 12 строчці треба додати `else`, бо якщо не додати, то на 18 строчці зайвий раз будуть операції

2023-01-11 14:28 UTC, mibal-ua commented on Tasks Kovalenko (Java)/Ip.java
> +        String[] splittedIP = IP.split("[.]");
Краще але не критично переписати `splittedIP` в CamelCase стилі, тобто `splittedIp`.

2023-01-11 14:28 UTC, mibal-ua commented on Tasks Kovalenko (Java)/Ip.java
> +        if (splittedIP.length==4) {
Перевір пліз стиль коду: `.length==4`, а треба `.length == 4`.

PS: в IntelliJ IDEA це можна зробити за допомогою `ctrl` + `alt` + `L`.

2023-01-11 14:36 UTC, merrymike-noname commented on Tasks Kovalenko (Java)/Ip.java
> +    public static Object[] parseIP (final String IP){
За конвенцією змінні-константи зазвичай називають капсом.

2023-01-11 16:28 UTC, mibal-ua commented on Tasks Kovalenko (Java)/Ip.java
> +    public static Object[] parseIP (final String IP){
ну вона ж не константа)) константи статичні та файнал, ця ж ні)

2023-01-11 16:38 UTC, merrymike-noname commented on Tasks Kovalenko (Java)/Ip.java
> +    public static Object[] parseIP (final String IP){
Помилився, визнаю)

2023-01-25 08:58 UTC, tshemsedinov commented on Tasks Kovalenko (Java)/Distinct.java
> +    public static List<Object> distinct(Object[] input) {
Naming hint: `ArrayUtils.distinct`

2023-01-25 08:59 UTC, tshemsedinov commented on Tasks Kovalenko (Java)/Distinct.java
> +}
Git and github requires one empty line at the end of each file

2023-01-25 09:00 UTC, tshemsedinov commented on Tasks Kovalenko (Java)/Ip.java
> +    public static Object[] parseIP(final String ip) {
```suggestion
    public static Object[] parse(final String ip) {
```

2023-01-25 09:01 UTC, tshemsedinov commented on Tasks Kovalenko (Java)/Ip.java
> +        if (splittedIp.length == 4) {
Use return early pattern
```suggestion
        if (splittedIp.length == 4) return null;
```

2023-01-25 09:02 UTC, tshemsedinov commented on Tasks Kovalenko (Java)/Ip.java
> +                    result.add(Integer.parseInt(element));
Add `{}` for multiline statements for readability
```suggestion
                if (element.matches(NUMERIC_REGEX)) {
                    result.add(Integer.parseInt(element));
                }
```

2023-01-25 09:03 UTC, closed without merging