Exams by Vlad Tokar IM21
HowProgrammingWorks/Exams pull request #174
Opened 2023-01-11 20:39 UTC by Vladyulik

Refactored quotes.js and words.js

2023-01-11 20:47 UTC, kovaliovev requested changes

2023-01-11 20:47 UTC, kovaliovev commented on Tasks/quotes.js
> +const quotes = (string) => {
It would be better to name function as `changeQuotes` for clarity.

2023-01-11 20:49 UTC, sonakrrr requested changes

2023-01-11 20:49 UTC, sonakrrr commented on Tasks/words.js
> +const words = (string) => {
`countWords` would be a better name for the function

2023-01-11 21:21 UTC, kovaliovev approved these changes
Great work!

2023-01-11 21:21 UTC, sonakrrr approved these changes
you did good!

2023-01-24 17:16 UTC, tshemsedinov commented on Tasks/quotes.js
> +      !open ? char = '«' : char = '»';
Incorrect usage of ternary semantics:
```suggestion
      char = !open ? '«' : '»';
```

2023-01-24 17:18 UTC, closed without merging

2023-01-24 19:14 UTC, Vladyulik commented
fixed all the problems 
https://github.com/HowProgrammingWorks/Exams/commit/d0a4eb4cdf9d20427c06fdaadafc6d24e55ce899

24 січня 2023, 19:16:57, від "Timur Shemsedinov" ***@***.***>:


@tshemsedinov commented on this pull request.
In Tasks/quotes.js:
> -          res.push('»');
-          open = false;
-        }
-      }
-    } else {
-      if (c !== '"') {
-        for (i of c) {
-          res.push(i);
-        }
-      }
+const changeQuotes = (string) => {
+  const result = [];
+  let open = false;
+  for (let char of string) {
+    if (char === '"') {
+      !open ? char = '«' : char = '»';
Incorrect usage of ternary semantics:
⬇️ Suggested change -      !open ? char = '«' : char = '»';
+      char = !open ? '«' : '»';
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>