Exams by Sofiia Krytska IM-21
HowProgrammingWorks/Exams pull request #176
Opened 2023-01-11 20:57 UTC by sonakrrr

Refactored types.js and intersection.js

2023-01-11 21:02 UTC, Vladyulik requested changes

2023-01-11 21:02 UTC, Vladyulik commented on Tasks/types.js
> +  const resObj = {
It would be better to rename `resObj` to just `result`

2023-01-11 21:04 UTC, kovaliovev requested changes

2023-01-11 21:04 UTC, kovaliovev commented on Tasks/intersection.js
> +  const intersectionObj = {};
Consider renaming `intersectionObj` to just `result`

2023-01-11 21:28 UTC, kovaliovev approved these changes
All is good now!

2023-01-11 21:29 UTC, Vladyulik approved these changes
Now that's what I call a perfect code!

2023-01-25 09:12 UTC, tshemsedinov approved these changes
LGTM (looks good to me)

2023-01-25 09:12 UTC, tshemsedinov commented on Tasks/intersection.js
> +'use strict'
```suggestion
'use strict';
```

2023-01-25 09:12 UTC, tshemsedinov commented on Tasks/intersection.js
> +      result[key] = obj1[key];
```suggestion
    const value = obj1[key];
    if (obj2[key] === value) {
      result[key] = value;
```

2023-01-25 09:13 UTC, closed without merging