Лєпков Б.М, ІМ-23
HowProgrammingWorks/Exams pull request #199
Opened 2023-01-13 21:04 UTC by nevrodegenerate

2023-01-13 21:44 UTC, v-jester commented on Tasks/between.js
> +const getvaluebetween = (fullString, startString, endString) => {
```suggestion
const getValueBetween = (fullString, startString, endString) => {
```
code style not visible

2023-01-25 03:21 UTC, tshemsedinov requested changes
- Code style and formatting is terrible
- Use eslint and prettier before commits
- You need to view almast all lectures again and try to implement all tasks for practice

2023-01-25 03:21 UTC, tshemsedinov commented on Tasks/month.js
> +const Month = (inputString) => {
Use `camelCase`

2023-01-25 03:21 UTC, tshemsedinov commented on Tasks/password.js
> +  for (let i = 0; i < passLength; i++) password += alphabet[Math.floor(Math.random() * alphabet.length)];
Use `{}` blocks

2023-01-25 03:21 UTC, tshemsedinov commented on Tasks/password.js
> +  for (let i = 0; i < passLength; i++) password += alphabet[Math.floor(Math.random() * alphabet.length)];
I'd prefer to extract `random` to a separate function

2023-01-25 03:21 UTC, tshemsedinov commented on Tasks/quotes.js
> +const quotes = function (inputString) {
Prefer arrow-functions
```suggestion
const quotes = (inputString) => {
```

2023-01-25 03:21 UTC, tshemsedinov commented on Tasks/quotes.js
> +  for (const SYMBOL of inputString) {
```suggestion
  for (const char of inputString) {
```

2023-01-25 03:21 UTC, tshemsedinov commented on Tasks/quotes.js
> +          outputString += '«';
Use ternary for open/close quotes

2023-01-25 03:21 UTC, tshemsedinov commented on Tasks/quotes.js
>          }
`open = !open`

2023-01-25 03:21 UTC, closed without merging