Exams by Sachko Maxim from group IM-22
HowProgrammingWorks/Exams pull request #203
Opened 2023-01-14 13:34 UTC by SachkoMaxim

Did the assignment for the exam.

2023-01-14 14:23 UTC, mibal-ua requested changes
Маєш круті назви змінних, але є, що виправити.

2023-01-14 14:23 UTC, mibal-ua commented on Tasks/replace.js
>    } else {
Тут не треба `} else {` бо якщо вище в if буде true, то все одно.

2023-01-14 14:23 UTC, mibal-ua commented on Tasks/replace.js
>        } else {
Тут теж `else` не потрібен.

2023-01-14 14:23 UTC, mibal-ua commented on Tasks/replace.js
> +    let res = '';
Краще назвати змінну `res` як `accumulator`. На мій погляд так логічніше, але не принципово.

2023-01-14 14:23 UTC, mibal-ua commented on Tasks/replace.js
> +      const stringIndex = changeString.indexOf(subString);
Краще `stringIndex` назви просто `index`, бо так лагонічніше код буде виглядати.

2023-01-14 14:23 UTC, mibal-ua commented on Tasks/zip.js
> +      delete arr1[i++];
Такс, не можна видаляти елементи масиву, бо це вплине на початковий масив. Тобто масив передається за посиланням, а не за  значенням, тому не можна видаляти дані з вхідних даних.

2023-01-16 14:53 UTC, mibal-ua reviewed
Супер!

2023-01-24 17:06 UTC, tshemsedinov commented on Tasks/day.js
> +const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
DAYS

2023-01-24 17:07 UTC, tshemsedinov commented on Tasks/plane.js
> +      res.push(element);
```suggestion
    const elements = Array.isArray(element) ? planeArray(element) : [element]
    res.push(...elements);
```

2023-01-24 17:08 UTC, tshemsedinov commented on Tasks/zip.js
> +  const length = arr1.length > arr2.length ? arr2.length : arr1.length;
Math.min

2023-01-24 17:10 UTC, closed without merging