Exams by Anastasia Dyvnich IM-23
HowProgrammingWorks/Exams pull request #214
Opened 2023-01-15 11:26 UTC by anastasiadyvnich

2023-01-15 21:14 UTC, karoll1naa requested changes

2023-01-15 21:14 UTC, karoll1naa commented on Tasks/distinct.js
> +}
Clean and high-quality code. Good job!

2023-01-24 16:57 UTC, tshemsedinov approved these changes
LGTM

2023-01-24 16:57 UTC, tshemsedinov commented on Tasks/distinct.js
> +const deduplicate = ([...arr]) => {
We do not need to clone array if we do not going to change it in function

2023-01-24 16:57 UTC, tshemsedinov commented on Tasks/difference.js
> +  for (const key in obj2) {
Prefer for..of loops

2023-01-24 16:57 UTC, tshemsedinov commented on Tasks/difference.js
> +    delete obj1[key];
It will be better to add keys for new result object than `delete` kays, I'd prefer to avoid `delete` in most cases if we have a choice

2023-01-24 16:57 UTC, closed without merging