Exams by Stas Yukhymenko IM-23
HowProgrammingWorks/Exams pull request #219
Opened 2023-01-15 18:06 UTC by stasyukhymenko

I've completed 2 tasks:
1. sum.js
2. intersection.js

2023-01-20 19:15 UTC, Nastia0703 reviewed
Good job!

2023-01-20 20:55 UTC, illiakroshka commented on Tasks/sum.js
> +const sumOfArray = (args) => {
```suggestion
const sumOfArray = args => {
```
If there is one function parameter, you can pass it without brackets

2023-01-24 16:32 UTC, tshemsedinov requested changes

2023-01-24 16:32 UTC, tshemsedinov commented on Tasks/intersection.js
> +            : delete object1[key];
Use ternary only to branch calculations not to branch control flow, so do not put assign `=` operator and  `delete` operator inside ternary

2023-01-24 16:32 UTC, tshemsedinov commented on Tasks/sum.js
> +"use strict";
Check your code with eslint and prettier before commit

2023-01-24 16:32 UTC, tshemsedinov commented on Tasks/sum.js
> +    result = typeof value === "number" ? (result += value) : result;
Use if in this case

2023-01-24 16:33 UTC, closed without merging